default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['DB_PASSWORD']%>
  host: <%= ENV['DB_HOST']%>
  port: <%= ENV['DB_PORT']%>
  database: <%= ENV['PGDATABASE']%>


development:
  <<: *default
  schema_search_path: dev, public


test:
  <<: *default
  schema_search_path: test
  database_tasks: false
  prepared_statements: false

production:
    <<: *default
    schema_search_path: prod
